### ISSUE TITLE
add http in metadata.txt homepage

### ISSUE THREAD

**Issue by luipir** [Ghini/DistanceMatrixToCoords#4]
in https://github.com/Ghini/DistanceMatrixToCoords/blob/master/metadata.txt

the homepage tag is not a URI, you have to add http:// otherwise the home page in http://plugins.qgis.org/plugins/DistanceMatrixToCoords/ ponts to: http://plugins.qgis.org/plugins/DistanceMatrixToCoords/ghini.github.io

**Comment by mfrasca** [comment]
thanks for reporting!

**Comment by luipir** [comment]
nP :), but you should update the version on plugin repo too

**Comment by mfrasca** [comment]
yes, I realized I was missing that point as soon as I saw there was a new notification on this subject !!
:rofl: I will do so as soon as I have finished some edits.

**Comment by mfrasca** [comment]
done. (took time: bad internet here) ... thanks for alerting.

**Comment by luipir** [comment]
verified... now works correctly, thank you
